# Generated by Django 3.2.10 on 2024-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20241014_1938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='androidapp',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='androidapp',
            name='subCategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='androidapp',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
